# Generated by Django 5.0.7 on 2024-07-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='集群列表序号')),
                ('cluster_name', models.CharField(max_length=50, verbose_name='集群名称')),
                ('cluster_nn_ip', models.CharField(max_length=50, verbose_name='集群nn ip')),
                ('cluster_id', models.CharField(default='NULL', max_length=50, verbose_name='集群id')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity', models.IntegerField()),
                ('used_capacity', models.IntegerField(default=0)),
                ('remaining_capacity', models.IntegerField()),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdfs_analyze.cluster', verbose_name='集群id')),
            ],
        ),
        migrations.CreateModel(
            name='DNInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_nodes', models.IntegerField()),
                ('live_nodes', models.IntegerField()),
                ('dead_nodes', models.IntegerField()),
                ('decommissioned_nodes', models.IntegerField()),
                ('decommissioning_nodes', models.IntegerField()),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdfs_analyze.cluster', verbose_name='集群id')),
            ],
        ),
        migrations.CreateModel(
            name='DNList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_list', models.TextField(verbose_name='对应状态节点列表')),
                ('status', models.CharField(max_length=50)),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdfs_analyze.cluster', verbose_name='所属集群')),
            ],
        ),
    ]
