# Generated by Django 5.0.7 on 2024-07-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdfs_analyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterinfo',
            name='remaining_capacity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clusterinfo',
            name='total_capacity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clusterinfo',
            name='used_capacity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
