# Generated by Django 5.0.7 on 2024-07-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdfs_analyze', '0002_alter_clusterinfo_remaining_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='cluster_id',
            field=models.CharField(default='NULL', max_length=50, unique=True, verbose_name='集群id'),
        ),
    ]
