# Generated by Django 5.0.7 on 2024-07-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdfs_analyze', '0003_alter_cluster_cluster_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='cluster_nn_ip',
        ),
        migrations.CreateModel(
            name='NNInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nn_ip', models.CharField(max_length=50, verbose_name='NN ip')),
                ('nn_role', models.CharField(max_length=30, verbose_name='NN role')),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdfs_analyze.cluster', verbose_name='所属集群')),
            ],
        ),
    ]
